### ISSUE TITLE
[FEATURE] php-dio for a better console logging

### ISSUE THREAD

**Issue by sgc-fireball** [shopware/docker#117]
Hi,
I would like to suggest and discuss whether it makes sense to install the PHP extension DIO.
The reason is that the PHP extension DIO is needed to redirect the log output to `/proc/1/fd/1` and `/proc/1/fd/2`.
PHP itself is not able to write to these `STDOUT` / `STDERR` devices by default with monolog / fopen.
An output to php://stdout is NOT the same as `/proc/1/fd/1` inside of docker containers!

This is especially noticeable when starting console programmes.

Inside docker container we should not write log files under `./var/log`, we should redirect it to the first pid of docker, that the logs are stored inside `docker logs`. For this, we need to redirect the output to `/proc/1/fd/`, `/proc/1/fd/2`.
We need three things for this:

1. php-dio
2. for example: `ziffmedia/monolog-dio-handler`
3. `config/packages/monolog.yaml` like this

```yaml
monolog:
  handlers:
    stdout:
      type: "service"
      id: "monolog_handlers_dio_stdout"
      channels: [ "!event", "!doctrine", "!console", "!messenger", "!php" ]
    stderr:
      type: "service"
      id: "monolog_handlers_dio_stderr"
      channels: [ "!event" ]

services:
  monolog_handlers_dio_stdout:
    class: ZiffMedia\MonologDioHandler\MonologDioHandler
    arguments:
      $path: "/proc/1/fd/1"
      $level: "info"
      $bubble: true
      $formatter: '@monolog.formatter.logstash'
  monolog_handlers_dio_stderr:
    class: ZiffMedia\MonologDioHandler\MonologDioHandler
    arguments:
      $path: "/proc/1/fd/1"
      $level: "warning"
      $bubble: true
      $formatter: '@monolog.formatter.logstash'
```

The same thing, we need inside the `shopware-cli` container to build shopware.
