### ISSUE TITLE
Shopware 6 production docker behind reverse proxy

### ISSUE THREAD

**Issue by iTacco** [shopware/docker#82]
# Introduction
Hello, I am really thankful that this repo exists, but I have a problem. I am sorry if this question is not placed right here, but I am really frustrated.

I am trying so set up a running Shopware 6 container behind a caddy reverse proxy. Furthermore, I already read almost all articles and posts about this topic, but nothing helped me. Shopware is working properly using HTTP.

I hope I can find help here. Thanks in advance!

# Problem Mixed Content
![image](https://github.com/shopware/docker/assets/49469623/96210558-da17-497c-b5ec-8095fa2c19ba)
And some others with the same core problem:
Mixed Content: The page at '**https**://my.domain.de/admin' was loaded over HTTPS, but requested an insecure favicon '**http**://my.domain.de/bundles/administration/static/img/favicon/favicon-32x32.png?1716754526'. This request has been blocked; the content must be served over HTTPS.

# Setup
Caddyfile:
```
my.domain.de {
	reverse_proxy container-web-1:8000
}
```
Caddy reverse proxy `docker inspect`:
![image](https://github.com/shopware/docker/assets/49469623/e0738481-55a4-49f6-ba1d-6c0eb2a31279)

.app.env:
```
DATABASE_URL=mysql://shopware:shopware@db/shopware
APP_SECRET=c5317f0a92d0660c5fe2534a1dd38a90623091f85b0f87a410d70172466182b4
APP_URL=https://my.domain.de
INSTANCE_ID=8d793ad70f6c1feaaf6da6b9c61c797441fb7d735876819d871ed6555b7a76c1
INSTALL_LOCALE=de-DE
TRUSTED_PROXIES=127.0.0.1,REMOTE_ADDR
...
```
Also tested setting the TRUSTED_PROXIES to the IP of the caddy reverse proxy IP like seen in the screenshot above `TRUSTED_PROXIES=172.28.0.2`

Both containers are inside the same network.
 
---
The APP_URL is set to `https://my.domain.de`

---
config/packages/**framework.yaml**:
```yaml
framework:
    # shortcut for private IP address ranges of your proxy
    trusted_proxies: '127.0.0.1,REMOTE_ADDR'
    # trust *all* "X-Forwarded-*" headers
    trusted_headers: ['x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-prefix']
```

---
Created a shopware instance with following command:
`docker run  --rm -v $(pwd):$(pwd) -w $(pwd) -u $(id -u) ghcr.io/friendsofshopware/shopware-cli project create new_test 6.6.2.0`

compose.yml:
```yaml
version: "3.8"
networks:
    caddy_default:
        external: true

services:
    db:
        image: mysql:8.0
        networks:
            - caddy_default
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: 'shopware'
            MYSQL_USER: shopware
            MYSQL_PASSWORD: shopware
            MYSQL_DATABASE: shopware
        volumes:
            - mysql-data:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "$$MYSQL_USER", "-p$$MYSQL_PASSWORD"]
            interval: 30s
            timeout: 5s
            retries: 2

    init-perm:
        image: alpine
        networks:
            - caddy_default
        volumes:
            - files:/var/www/html/files
            - theme:/var/www/html/public/theme
            - media:/var/www/html/public/media
            - thumbnail:/var/www/html/public/thumbnail
            - sitemap:/var/www/html/public/sitemap
        command: chown 82:82 /var/www/html/files /var/www/html/public/theme /var/www/html/public/media /var/www/html/public/thumbnail /var/www/html/public/sitemap

    init:
        image: sw-base
        networks:
            - caddy_default
        build:
            context: .
        env_file: .app.env
        entrypoint: /setup
        volumes:
            - files:/var/www/html/files
            - theme:/var/www/html/public/theme
            - media:/var/www/html/public/media
            - thumbnail:/var/www/html/public/thumbnail
            - sitemap:/var/www/html/public/sitemap
        depends_on:
            db:
                condition: service_healthy
            init-perm:
                condition: service_completed_successfully

    phpmyadmin:
        image: phpmyadmin:latest
        restart: unless-stopped
        networks:
            - caddy_default
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        ports:
            - 8051:80
        depends_on:
            db:
                condition: service_healthy

    web:
        image: sw-base
        networks:
            - caddy_default
        restart: unless-stopped
        volumes:
            - files:/var/www/html/files
            - theme:/var/www/html/public/theme
            - media:/var/www/html/public/media
            - thumbnail:/var/www/html/public/thumbnail
            - sitemap:/var/www/html/public/sitemap
        depends_on:
            init:
                condition: service_completed_successfully
        env_file: .app.env

    worker:
        image: sw-base
        networks:
            - caddy_default
        restart: unless-stopped
        volumes:
            - files:/var/www/html/files
            - theme:/var/www/html/public/theme
            - media:/var/www/html/public/media
            - thumbnail:/var/www/html/public/thumbnail
            - sitemap:/var/www/html/public/sitemap
        depends_on:
            init:
                condition: service_completed_successfully
        env_file: .app.env
        entrypoint: [ "php", "bin/console", "messenger:consume", "async", "--time-limit=300", "--memory-limit=512M" ]
        deploy:
            replicas: 2

volumes:
    mysql-data:
    files:
    theme:
    media:
    thumbnail:
    sitemap:
```

Dockerfile:
```dockerfile
#syntax=docker/dockerfile:1.4

# pin versions
FROM ghcr.io/shopware/docker-base:8.2 as base-image
FROM ghcr.io/friendsofshopware/shopware-cli:latest-php-8.2 as shopware-cli

# build

FROM shopware-cli as build

COPY --link . /src
WORKDIR /src

RUN --mount=type=secret,id=composer_auth,dst=/src/auth.json \
    --mount=type=cache,target=/root/.composer \
    --mount=type=cache,target=/root/.npm \
    /usr/local/bin/entrypoint.sh shopware-cli project ci /src

RUN shopware-cli project generate-jwt /src

# build final image

FROM base-image
USER root
RUN apk add --no-cache git

USER www-data

COPY --from=build --chown=www-data /src /var/www/html
```

**Comment by MBDealer** [comment]
I have the same issue, it just runs with this setting: TRUSTED_PROXIES: 0.0.0.0/0

But that cannot be the solution.

**Comment by shyim** [comment]
I think you are missing this in your caddyfile:

```
my.domain.de {
	reverse_proxy container-web-1:8000 {
            trusted_proxies private_ranges
        }
}

```

**Comment by shyim** [comment]
You can run `ps -ax` and then you need to `kill -USR2 <pid-of-main-php-fpm`

The opcache is pretty aggresivve configured 😅

**Comment by iTacco** [comment]
Ah okay, this is the output:

![image](https://github.com/shopware/docker/assets/49469623/bd14bc73-42e4-43a4-b3ca-3784e2fad7bc)

**Comment by shyim** [comment]
there are no http forwarded headers. The webserver talking with the real browser does not forward them 🤔

**Comment by iTacco** [comment]
Interesting, do you have any suggestions what I can do to solve this problem. This is my phpinfo output. Maybe there is something which can tell more about the problem:
![image](https://github.com/shopware/docker/assets/49469623/2d7dd483-17f8-40aa-b00b-93ada8d1cef8)
![image](https://github.com/shopware/docker/assets/49469623/47c2fa23-20ca-420d-94b8-3c8b3969c9e6)

**Comment by aritas1** [comment]
@iTacco came across the same issue, exactly at the same time.
just force it in your enviroment (.app.env) or directly on the container, worked for me:
```
HTTPS=on
```

my headers where forwarded to php just fine. i couldn't find the location in the source code to debug it properly.
```
["REMOTE_ADDR"]=> string(11) "172.16.0.35"
["HTTP_X_FORWARDED_PROTO"]=> string(5) "https"
```

**Comment by shyim** [comment]
@aritas1 maybe you forgot to configure trusted_proxies in the yaml?

```
framework:
    # shortcut for private IP address ranges of your proxy
    trusted_proxies: '172.16.0.0/24'
    trusted_headers: ['x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-prefix']
```

should do it for your case i think 🤔

**Comment by iTacco** [comment]
I finally got it with the help of @shyim! Thank you very much. The actual problem was, that I was testing all the config parts in a running container without knowing that the opcache is so aggressivly configured. After a `bin/console cache:clear` followed by the suggestion of @shyim `kill -USR2 <pid_of_master_fpm>` it works with HTTPS as expected.

# My instruction to get it working
To all of you who maybe got into the same problem, this is my final setup and workflow which works for me:

## Showpare part
1. Created a Shopware 6 instance with
```bash
docker run --rm -v $(pwd):$(pwd) -w $(pwd) -u $(id -u) ghcr.io/friendsofshopware/shopware-cli project create <project-name> <shopware-version>
```
e.g.
```bash
docker run --rm -v $(pwd):$(pwd) -w $(pwd) -u $(id -u) ghcr.io/friendsofshopware/shopware-cli project create my-project 6.6.2.0
```
2. cd into the newly created folder
3. delete the existing `compose.yaml` and `compose.override.yaml` files
4. create a Dockerfile with following content:
```Dockerfile
#syntax=docker/dockerfile:1.4

# pin versions
FROM ghcr.io/shopware/docker-base:8.2 as base-image
FROM ghcr.io/friendsofshopware/shopware-cli:latest-php-8.2 as shopware-cli

# build

FROM shopware-cli as build

COPY --link . /src
WORKDIR /src

RUN --mount=type=secret,id=composer_auth,dst=/src/auth.json \
    --mount=type=cache,target=/root/.composer \
    --mount=type=cache,target=/root/.npm \
    /usr/local/bin/entrypoint.sh shopware-cli project ci /src

# Needed because otherwise the /admin gives following error:
# {"errors":[{"code":"0","status":"500","title":"Internal Server Error","detail":"The path \u0022\/var\/www\/html\/config\/jwt\/private.pem\u0022 does not contain a valid key file"}]}
RUN shopware-cli project generate-jwt /src

# build final image

FROM base-image
USER root
RUN apk add --no-cache git

USER www-data

COPY --from=build --chown=www-data /src /var/www/html
```

5. create a `compose.yml` file with following content:
```yaml
version: "3.8"
networks:
    caddy_default:
        external: true

services:
    db:
        image: mysql:8.0
        networks:
            - caddy_default
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: 'shopware'
            MYSQL_USER: shopware
            MYSQL_PASSWORD: shopware
            MYSQL_DATABASE: shopware
        volumes:
            - mysql-data:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "$$MYSQL_USER", "-p$$MYSQL_PASSWORD"]
            interval: 30s
            timeout: 5s
            retries: 2

    init-perm:
        image: alpine
        networks:
            - caddy_default
        volumes:
            - files:/var/www/html/files
            - theme:/var/www/html/public/theme
            - media:/var/www/html/public/media
            - thumbnail:/var/www/html/public/thumbnail
            - sitemap:/var/www/html/public/sitemap
        command: chown 82:82 /var/www/html/files /var/www/html/public/theme /var/www/html/public/media /var/www/html/public/thumbnail /var/www/html/public/sitemap

    init:
        image: sw-base
        networks:
            - caddy_default
        build:
            context: .
        env_file: .app.env
        entrypoint: /setup
        volumes:
            - files:/var/www/html/files
            - theme:/var/www/html/public/theme
            - media:/var/www/html/public/media
            - thumbnail:/var/www/html/public/thumbnail
            - sitemap:/var/www/html/public/sitemap
        depends_on:
            db:
                condition: service_healthy
            init-perm:
                condition: service_completed_successfully

    phpmyadmin:
        image: phpmyadmin:latest
        restart: unless-stopped
        networks:
            - caddy_default
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        depends_on:
            db:
                condition: service_healthy

    web:
        image: sw-base
        networks:
            - caddy_default
        restart: unless-stopped
        volumes:
            - files:/var/www/html/files
            - theme:/var/www/html/public/theme
            - media:/var/www/html/public/media
            - thumbnail:/var/www/html/public/thumbnail
            - sitemap:/var/www/html/public/sitemap
        depends_on:
            init:
                condition: service_completed_successfully
        env_file: .app.env

    worker:
        image: sw-base
        networks:
            - caddy_default
        restart: unless-stopped
        volumes:
            - files:/var/www/html/files
            - theme:/var/www/html/public/theme
            - media:/var/www/html/public/media
            - thumbnail:/var/www/html/public/thumbnail
            - sitemap:/var/www/html/public/sitemap
        depends_on:
            init:
                condition: service_completed_successfully
        env_file: .app.env
        entrypoint: [ "php", "bin/console", "messenger:consume", "async", "--time-limit=300", "--memory-limit=512M" ]
        deploy:
            replicas: 3

volumes:
    mysql-data:
    files:
    theme:
    media:
    thumbnail:
    sitemap:
```
6. Create `config/packages/framework.yaml` with following content:
```yaml
framework:
    trusted_proxies: '127.0.0.1,REMOTE_ADDR'
    trusted_headers: ['x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-prefix']
```
7. Create `.app.env` with following content:
```
DATABASE_URL=mysql://shopware:shopware@db/shopware
APP_SECRET=any-secret
APP_URL=https://your.domain
INSTANCE_ID=any-instance-id
TRUSTED_PROXIES=127.0.0.1,REMOTE_ADDR
```

## Caddy reverse proxy part:
Caddyfile:
```
your.domain {
        reverse_proxy <shopware-web-containername>:8000
}
```
Caddy compose.yml:
```yaml
services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
```

I hope it will help someone 👍
